# Online Dataset
url_dataset: 'https://www.dropbox.com/s/b8ykxt604zcymfr/proyecto-grados.zip?dl=1'
compressed_data_name: 'proyecto-grados.zip'

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_climatic: 'climatic'
data_dir_climatic_images: 'Climatic Images'
data_dir_series: 'Series'
data_dir_xm: 'xm'
downloads_dir: 'downloads'

# Data Files
meteorologic_stations_data_file: 'Estaciones Meteorologicas Colombia V1.csv'